/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Members": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Members.id"];
          UserId?: parameters["rowFilter.Members.UserId"];
          registration_email?: parameters["rowFilter.Members.registration_email"];
          name?: parameters["rowFilter.Members.name"];
          phone?: parameters["rowFilter.Members.phone"];
          address?: parameters["rowFilter.Members.address"];
          discount?: parameters["rowFilter.Members.discount"];
          discount_type?: parameters["rowFilter.Members.discount_type"];
          fees_paid?: parameters["rowFilter.Members.fees_paid"];
          store_credit?: parameters["rowFilter.Members.store_credit"];
          shares?: parameters["rowFilter.Members.shares"];
          member_type?: parameters["rowFilter.Members.member_type"];
          data?: parameters["rowFilter.Members.data"];
          createdAt?: parameters["rowFilter.Members.createdAt"];
          updatedAt?: parameters["rowFilter.Members.updatedAt"];
          /** admin user */
          is_admin?: parameters["rowFilter.Members.is_admin"];
          fts?: parameters["rowFilter.Members.fts"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Members"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Members */
          Members?: definitions["Members"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Members.id"];
          UserId?: parameters["rowFilter.Members.UserId"];
          registration_email?: parameters["rowFilter.Members.registration_email"];
          name?: parameters["rowFilter.Members.name"];
          phone?: parameters["rowFilter.Members.phone"];
          address?: parameters["rowFilter.Members.address"];
          discount?: parameters["rowFilter.Members.discount"];
          discount_type?: parameters["rowFilter.Members.discount_type"];
          fees_paid?: parameters["rowFilter.Members.fees_paid"];
          store_credit?: parameters["rowFilter.Members.store_credit"];
          shares?: parameters["rowFilter.Members.shares"];
          member_type?: parameters["rowFilter.Members.member_type"];
          data?: parameters["rowFilter.Members.data"];
          createdAt?: parameters["rowFilter.Members.createdAt"];
          updatedAt?: parameters["rowFilter.Members.updatedAt"];
          /** admin user */
          is_admin?: parameters["rowFilter.Members.is_admin"];
          fts?: parameters["rowFilter.Members.fts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Members.id"];
          UserId?: parameters["rowFilter.Members.UserId"];
          registration_email?: parameters["rowFilter.Members.registration_email"];
          name?: parameters["rowFilter.Members.name"];
          phone?: parameters["rowFilter.Members.phone"];
          address?: parameters["rowFilter.Members.address"];
          discount?: parameters["rowFilter.Members.discount"];
          discount_type?: parameters["rowFilter.Members.discount_type"];
          fees_paid?: parameters["rowFilter.Members.fees_paid"];
          store_credit?: parameters["rowFilter.Members.store_credit"];
          shares?: parameters["rowFilter.Members.shares"];
          member_type?: parameters["rowFilter.Members.member_type"];
          data?: parameters["rowFilter.Members.data"];
          createdAt?: parameters["rowFilter.Members.createdAt"];
          updatedAt?: parameters["rowFilter.Members.updatedAt"];
          /** admin user */
          is_admin?: parameters["rowFilter.Members.is_admin"];
          fts?: parameters["rowFilter.Members.fts"];
        };
        body: {
          /** Members */
          Members?: definitions["Members"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/OrderLineItems": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.OrderLineItems.id"];
          OrderId?: parameters["rowFilter.OrderLineItems.OrderId"];
          WholesaleOrderId?: parameters["rowFilter.OrderLineItems.WholesaleOrderId"];
          price?: parameters["rowFilter.OrderLineItems.price"];
          quantity?: parameters["rowFilter.OrderLineItems.quantity"];
          total?: parameters["rowFilter.OrderLineItems.total"];
          kind?: parameters["rowFilter.OrderLineItems.kind"];
          description?: parameters["rowFilter.OrderLineItems.description"];
          vendor?: parameters["rowFilter.OrderLineItems.vendor"];
          selected_unit?: parameters["rowFilter.OrderLineItems.selected_unit"];
          data?: parameters["rowFilter.OrderLineItems.data"];
          createdAt?: parameters["rowFilter.OrderLineItems.createdAt"];
          updatedAt?: parameters["rowFilter.OrderLineItems.updatedAt"];
          status?: parameters["rowFilter.OrderLineItems.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["OrderLineItems"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** OrderLineItems */
          OrderLineItems?: definitions["OrderLineItems"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.OrderLineItems.id"];
          OrderId?: parameters["rowFilter.OrderLineItems.OrderId"];
          WholesaleOrderId?: parameters["rowFilter.OrderLineItems.WholesaleOrderId"];
          price?: parameters["rowFilter.OrderLineItems.price"];
          quantity?: parameters["rowFilter.OrderLineItems.quantity"];
          total?: parameters["rowFilter.OrderLineItems.total"];
          kind?: parameters["rowFilter.OrderLineItems.kind"];
          description?: parameters["rowFilter.OrderLineItems.description"];
          vendor?: parameters["rowFilter.OrderLineItems.vendor"];
          selected_unit?: parameters["rowFilter.OrderLineItems.selected_unit"];
          data?: parameters["rowFilter.OrderLineItems.data"];
          createdAt?: parameters["rowFilter.OrderLineItems.createdAt"];
          updatedAt?: parameters["rowFilter.OrderLineItems.updatedAt"];
          status?: parameters["rowFilter.OrderLineItems.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.OrderLineItems.id"];
          OrderId?: parameters["rowFilter.OrderLineItems.OrderId"];
          WholesaleOrderId?: parameters["rowFilter.OrderLineItems.WholesaleOrderId"];
          price?: parameters["rowFilter.OrderLineItems.price"];
          quantity?: parameters["rowFilter.OrderLineItems.quantity"];
          total?: parameters["rowFilter.OrderLineItems.total"];
          kind?: parameters["rowFilter.OrderLineItems.kind"];
          description?: parameters["rowFilter.OrderLineItems.description"];
          vendor?: parameters["rowFilter.OrderLineItems.vendor"];
          selected_unit?: parameters["rowFilter.OrderLineItems.selected_unit"];
          data?: parameters["rowFilter.OrderLineItems.data"];
          createdAt?: parameters["rowFilter.OrderLineItems.createdAt"];
          updatedAt?: parameters["rowFilter.OrderLineItems.updatedAt"];
          status?: parameters["rowFilter.OrderLineItems.status"];
        };
        body: {
          /** OrderLineItems */
          OrderLineItems?: definitions["OrderLineItems"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/Orders": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Orders.id"];
          UserId?: parameters["rowFilter.Orders.UserId"];
          status?: parameters["rowFilter.Orders.status"];
          payment_status?: parameters["rowFilter.Orders.payment_status"];
          shipment_status?: parameters["rowFilter.Orders.shipment_status"];
          total?: parameters["rowFilter.Orders.total"];
          subtotal?: parameters["rowFilter.Orders.subtotal"];
          name?: parameters["rowFilter.Orders.name"];
          email?: parameters["rowFilter.Orders.email"];
          phone?: parameters["rowFilter.Orders.phone"];
          address?: parameters["rowFilter.Orders.address"];
          notes?: parameters["rowFilter.Orders.notes"];
          email_sent?: parameters["rowFilter.Orders.email_sent"];
          item_count?: parameters["rowFilter.Orders.item_count"];
          history?: parameters["rowFilter.Orders.history"];
          createdAt?: parameters["rowFilter.Orders.createdAt"];
          updatedAt?: parameters["rowFilter.Orders.updatedAt"];
          MemberId?: parameters["rowFilter.Orders.MemberId"];
          fts?: parameters["rowFilter.Orders.fts"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Orders"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Orders */
          Orders?: definitions["Orders"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Orders.id"];
          UserId?: parameters["rowFilter.Orders.UserId"];
          status?: parameters["rowFilter.Orders.status"];
          payment_status?: parameters["rowFilter.Orders.payment_status"];
          shipment_status?: parameters["rowFilter.Orders.shipment_status"];
          total?: parameters["rowFilter.Orders.total"];
          subtotal?: parameters["rowFilter.Orders.subtotal"];
          name?: parameters["rowFilter.Orders.name"];
          email?: parameters["rowFilter.Orders.email"];
          phone?: parameters["rowFilter.Orders.phone"];
          address?: parameters["rowFilter.Orders.address"];
          notes?: parameters["rowFilter.Orders.notes"];
          email_sent?: parameters["rowFilter.Orders.email_sent"];
          item_count?: parameters["rowFilter.Orders.item_count"];
          history?: parameters["rowFilter.Orders.history"];
          createdAt?: parameters["rowFilter.Orders.createdAt"];
          updatedAt?: parameters["rowFilter.Orders.updatedAt"];
          MemberId?: parameters["rowFilter.Orders.MemberId"];
          fts?: parameters["rowFilter.Orders.fts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.Orders.id"];
          UserId?: parameters["rowFilter.Orders.UserId"];
          status?: parameters["rowFilter.Orders.status"];
          payment_status?: parameters["rowFilter.Orders.payment_status"];
          shipment_status?: parameters["rowFilter.Orders.shipment_status"];
          total?: parameters["rowFilter.Orders.total"];
          subtotal?: parameters["rowFilter.Orders.subtotal"];
          name?: parameters["rowFilter.Orders.name"];
          email?: parameters["rowFilter.Orders.email"];
          phone?: parameters["rowFilter.Orders.phone"];
          address?: parameters["rowFilter.Orders.address"];
          notes?: parameters["rowFilter.Orders.notes"];
          email_sent?: parameters["rowFilter.Orders.email_sent"];
          item_count?: parameters["rowFilter.Orders.item_count"];
          history?: parameters["rowFilter.Orders.history"];
          createdAt?: parameters["rowFilter.Orders.createdAt"];
          updatedAt?: parameters["rowFilter.Orders.updatedAt"];
          MemberId?: parameters["rowFilter.Orders.MemberId"];
          fts?: parameters["rowFilter.Orders.fts"];
        };
        body: {
          /** Orders */
          Orders?: definitions["Orders"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/WholesaleOrders": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.WholesaleOrders.id"];
          vendor?: parameters["rowFilter.WholesaleOrders.vendor"];
          notes?: parameters["rowFilter.WholesaleOrders.notes"];
          status?: parameters["rowFilter.WholesaleOrders.status"];
          payment_status?: parameters["rowFilter.WholesaleOrders.payment_status"];
          shipment_status?: parameters["rowFilter.WholesaleOrders.shipment_status"];
          createdAt?: parameters["rowFilter.WholesaleOrders.createdAt"];
          updatedAt?: parameters["rowFilter.WholesaleOrders.updatedAt"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["WholesaleOrders"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** WholesaleOrders */
          WholesaleOrders?: definitions["WholesaleOrders"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.WholesaleOrders.id"];
          vendor?: parameters["rowFilter.WholesaleOrders.vendor"];
          notes?: parameters["rowFilter.WholesaleOrders.notes"];
          status?: parameters["rowFilter.WholesaleOrders.status"];
          payment_status?: parameters["rowFilter.WholesaleOrders.payment_status"];
          shipment_status?: parameters["rowFilter.WholesaleOrders.shipment_status"];
          createdAt?: parameters["rowFilter.WholesaleOrders.createdAt"];
          updatedAt?: parameters["rowFilter.WholesaleOrders.updatedAt"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.WholesaleOrders.id"];
          vendor?: parameters["rowFilter.WholesaleOrders.vendor"];
          notes?: parameters["rowFilter.WholesaleOrders.notes"];
          status?: parameters["rowFilter.WholesaleOrders.status"];
          payment_status?: parameters["rowFilter.WholesaleOrders.payment_status"];
          shipment_status?: parameters["rowFilter.WholesaleOrders.shipment_status"];
          createdAt?: parameters["rowFilter.WholesaleOrders.createdAt"];
          updatedAt?: parameters["rowFilter.WholesaleOrders.updatedAt"];
        };
        body: {
          /** WholesaleOrders */
          WholesaleOrders?: definitions["WholesaleOrders"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          unf?: parameters["rowFilter.products.unf"];
          upc_code?: parameters["rowFilter.products.upc_code"];
          category?: parameters["rowFilter.products.category"];
          sub_category?: parameters["rowFilter.products.sub_category"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          pk?: parameters["rowFilter.products.pk"];
          size?: parameters["rowFilter.products.size"];
          unit_type?: parameters["rowFilter.products.unit_type"];
          ws_price?: parameters["rowFilter.products.ws_price"];
          u_price?: parameters["rowFilter.products.u_price"];
          ws_price_cost?: parameters["rowFilter.products.ws_price_cost"];
          u_price_cost?: parameters["rowFilter.products.u_price_cost"];
          codes?: parameters["rowFilter.products.codes"];
          vendor?: parameters["rowFilter.products.vendor"];
          import_tag?: parameters["rowFilter.products.import_tag"];
          createdAt?: parameters["rowFilter.products.createdAt"];
          updatedAt?: parameters["rowFilter.products.updatedAt"];
          count_on_hand?: parameters["rowFilter.products.count_on_hand"];
          no_backorder?: parameters["rowFilter.products.no_backorder"];
          fts?: parameters["rowFilter.products.fts"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          unf?: parameters["rowFilter.products.unf"];
          upc_code?: parameters["rowFilter.products.upc_code"];
          category?: parameters["rowFilter.products.category"];
          sub_category?: parameters["rowFilter.products.sub_category"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          pk?: parameters["rowFilter.products.pk"];
          size?: parameters["rowFilter.products.size"];
          unit_type?: parameters["rowFilter.products.unit_type"];
          ws_price?: parameters["rowFilter.products.ws_price"];
          u_price?: parameters["rowFilter.products.u_price"];
          ws_price_cost?: parameters["rowFilter.products.ws_price_cost"];
          u_price_cost?: parameters["rowFilter.products.u_price_cost"];
          codes?: parameters["rowFilter.products.codes"];
          vendor?: parameters["rowFilter.products.vendor"];
          import_tag?: parameters["rowFilter.products.import_tag"];
          createdAt?: parameters["rowFilter.products.createdAt"];
          updatedAt?: parameters["rowFilter.products.updatedAt"];
          count_on_hand?: parameters["rowFilter.products.count_on_hand"];
          no_backorder?: parameters["rowFilter.products.no_backorder"];
          fts?: parameters["rowFilter.products.fts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          unf?: parameters["rowFilter.products.unf"];
          upc_code?: parameters["rowFilter.products.upc_code"];
          category?: parameters["rowFilter.products.category"];
          sub_category?: parameters["rowFilter.products.sub_category"];
          name?: parameters["rowFilter.products.name"];
          description?: parameters["rowFilter.products.description"];
          pk?: parameters["rowFilter.products.pk"];
          size?: parameters["rowFilter.products.size"];
          unit_type?: parameters["rowFilter.products.unit_type"];
          ws_price?: parameters["rowFilter.products.ws_price"];
          u_price?: parameters["rowFilter.products.u_price"];
          ws_price_cost?: parameters["rowFilter.products.ws_price_cost"];
          u_price_cost?: parameters["rowFilter.products.u_price_cost"];
          codes?: parameters["rowFilter.products.codes"];
          vendor?: parameters["rowFilter.products.vendor"];
          import_tag?: parameters["rowFilter.products.import_tag"];
          createdAt?: parameters["rowFilter.products.createdAt"];
          updatedAt?: parameters["rowFilter.products.updatedAt"];
          count_on_hand?: parameters["rowFilter.products.count_on_hand"];
          no_backorder?: parameters["rowFilter.products.no_backorder"];
          fts?: parameters["rowFilter.products.fts"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/stock": {
    get: {
      parameters: {
        query: {
          variation_id?: parameters["rowFilter.stock.variation_id"];
          name?: parameters["rowFilter.stock.name"];
          description?: parameters["rowFilter.stock.description"];
          price?: parameters["rowFilter.stock.price"];
          unit?: parameters["rowFilter.stock.unit"];
          quantity?: parameters["rowFilter.stock.quantity"];
          sku?: parameters["rowFilter.stock.sku"];
          item_id?: parameters["rowFilter.stock.item_id"];
          created_at?: parameters["rowFilter.stock.created_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["stock"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** stock */
          stock?: definitions["stock"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          variation_id?: parameters["rowFilter.stock.variation_id"];
          name?: parameters["rowFilter.stock.name"];
          description?: parameters["rowFilter.stock.description"];
          price?: parameters["rowFilter.stock.price"];
          unit?: parameters["rowFilter.stock.unit"];
          quantity?: parameters["rowFilter.stock.quantity"];
          sku?: parameters["rowFilter.stock.sku"];
          item_id?: parameters["rowFilter.stock.item_id"];
          created_at?: parameters["rowFilter.stock.created_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          variation_id?: parameters["rowFilter.stock.variation_id"];
          name?: parameters["rowFilter.stock.name"];
          description?: parameters["rowFilter.stock.description"];
          price?: parameters["rowFilter.stock.price"];
          unit?: parameters["rowFilter.stock.unit"];
          quantity?: parameters["rowFilter.stock.quantity"];
          sku?: parameters["rowFilter.stock.sku"];
          item_id?: parameters["rowFilter.stock.item_id"];
          created_at?: parameters["rowFilter.stock.created_at"];
        };
        body: {
          /** stock */
          stock?: definitions["stock"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/distinct_product_sub_categories": {
    post: {
      parameters: {
        body: {
          args: {
            category: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/distinct_product_categories": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  Members: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    UserId?: string;
    registration_email?: string;
    name?: string;
    phone?: string;
    address?: string;
    discount?: number;
    discount_type?: string;
    fees_paid?: number;
    store_credit?: number;
    shares?: number;
    member_type?: string;
    data?: string;
    createdAt?: string;
    updatedAt?: string;
    /** admin user */
    is_admin: boolean;
    fts?: string;
  };
  OrderLineItems: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Note:
     * This is a Foreign Key to `Orders.id`.<fk table='Orders' column='id'/>
     */
    OrderId?: number;
    /**
     * Note:
     * This is a Foreign Key to `WholesaleOrders.id`.<fk table='WholesaleOrders' column='id'/>
     */
    WholesaleOrderId?: number;
    price?: number;
    quantity?: number;
    total?: number;
    kind?: string;
    description?: string;
    vendor?: string;
    selected_unit?: string;
    data?: string;
    createdAt?: string;
    updatedAt?: string;
    status?: string;
  };
  Orders: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    UserId?: string;
    status?: string;
    payment_status?: string;
    shipment_status?: string;
    total?: number;
    subtotal?: number;
    name?: string;
    email?: string;
    phone?: string;
    address?: string;
    notes?: string;
    email_sent?: boolean;
    item_count?: number;
    history?: string;
    createdAt?: string;
    updatedAt?: string;
    /**
     * Note:
     * This is a Foreign Key to `Members.id`.<fk table='Members' column='id'/>
     */
    MemberId?: number;
    fts?: string;
  };
  WholesaleOrders: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    vendor?: string;
    notes?: string;
    status?: string;
    payment_status?: string;
    shipment_status?: string;
    createdAt?: string;
    updatedAt?: string;
  };
  products: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    unf?: string;
    upc_code?: string;
    category?: string;
    sub_category?: string;
    name?: string;
    description?: string;
    pk?: number;
    size?: string;
    unit_type?: string;
    ws_price?: number;
    u_price?: number;
    ws_price_cost?: number;
    u_price_cost?: number;
    codes?: string;
    vendor?: string;
    import_tag?: string;
    createdAt?: string;
    updatedAt?: string;
    count_on_hand?: number;
    no_backorder?: boolean;
    fts?: string;
  };
  /** square on-hand inventory */
  stock: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    variation_id: string;
    name?: string;
    description?: string;
    price?: number;
    unit?: string;
    quantity?: number;
    sku?: string;
    item_id?: string;
    created_at?: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** Members */
  "body.Members": definitions["Members"];
  "rowFilter.Members.id": string;
  "rowFilter.Members.UserId": string;
  "rowFilter.Members.registration_email": string;
  "rowFilter.Members.name": string;
  "rowFilter.Members.phone": string;
  "rowFilter.Members.address": string;
  "rowFilter.Members.discount": string;
  "rowFilter.Members.discount_type": string;
  "rowFilter.Members.fees_paid": string;
  "rowFilter.Members.store_credit": string;
  "rowFilter.Members.shares": string;
  "rowFilter.Members.member_type": string;
  "rowFilter.Members.data": string;
  "rowFilter.Members.createdAt": string;
  "rowFilter.Members.updatedAt": string;
  /** admin user */
  "rowFilter.Members.is_admin": string;
  "rowFilter.Members.fts": string;
  /** OrderLineItems */
  "body.OrderLineItems": definitions["OrderLineItems"];
  "rowFilter.OrderLineItems.id": string;
  "rowFilter.OrderLineItems.OrderId": string;
  "rowFilter.OrderLineItems.WholesaleOrderId": string;
  "rowFilter.OrderLineItems.price": string;
  "rowFilter.OrderLineItems.quantity": string;
  "rowFilter.OrderLineItems.total": string;
  "rowFilter.OrderLineItems.kind": string;
  "rowFilter.OrderLineItems.description": string;
  "rowFilter.OrderLineItems.vendor": string;
  "rowFilter.OrderLineItems.selected_unit": string;
  "rowFilter.OrderLineItems.data": string;
  "rowFilter.OrderLineItems.createdAt": string;
  "rowFilter.OrderLineItems.updatedAt": string;
  "rowFilter.OrderLineItems.status": string;
  /** Orders */
  "body.Orders": definitions["Orders"];
  "rowFilter.Orders.id": string;
  "rowFilter.Orders.UserId": string;
  "rowFilter.Orders.status": string;
  "rowFilter.Orders.payment_status": string;
  "rowFilter.Orders.shipment_status": string;
  "rowFilter.Orders.total": string;
  "rowFilter.Orders.subtotal": string;
  "rowFilter.Orders.name": string;
  "rowFilter.Orders.email": string;
  "rowFilter.Orders.phone": string;
  "rowFilter.Orders.address": string;
  "rowFilter.Orders.notes": string;
  "rowFilter.Orders.email_sent": string;
  "rowFilter.Orders.item_count": string;
  "rowFilter.Orders.history": string;
  "rowFilter.Orders.createdAt": string;
  "rowFilter.Orders.updatedAt": string;
  "rowFilter.Orders.MemberId": string;
  "rowFilter.Orders.fts": string;
  /** WholesaleOrders */
  "body.WholesaleOrders": definitions["WholesaleOrders"];
  "rowFilter.WholesaleOrders.id": string;
  "rowFilter.WholesaleOrders.vendor": string;
  "rowFilter.WholesaleOrders.notes": string;
  "rowFilter.WholesaleOrders.status": string;
  "rowFilter.WholesaleOrders.payment_status": string;
  "rowFilter.WholesaleOrders.shipment_status": string;
  "rowFilter.WholesaleOrders.createdAt": string;
  "rowFilter.WholesaleOrders.updatedAt": string;
  /** products */
  "body.products": definitions["products"];
  "rowFilter.products.id": string;
  "rowFilter.products.unf": string;
  "rowFilter.products.upc_code": string;
  "rowFilter.products.category": string;
  "rowFilter.products.sub_category": string;
  "rowFilter.products.name": string;
  "rowFilter.products.description": string;
  "rowFilter.products.pk": string;
  "rowFilter.products.size": string;
  "rowFilter.products.unit_type": string;
  "rowFilter.products.ws_price": string;
  "rowFilter.products.u_price": string;
  "rowFilter.products.ws_price_cost": string;
  "rowFilter.products.u_price_cost": string;
  "rowFilter.products.codes": string;
  "rowFilter.products.vendor": string;
  "rowFilter.products.import_tag": string;
  "rowFilter.products.createdAt": string;
  "rowFilter.products.updatedAt": string;
  "rowFilter.products.count_on_hand": string;
  "rowFilter.products.no_backorder": string;
  "rowFilter.products.fts": string;
  /** stock */
  "body.stock": definitions["stock"];
  "rowFilter.stock.variation_id": string;
  "rowFilter.stock.name": string;
  "rowFilter.stock.description": string;
  "rowFilter.stock.price": string;
  "rowFilter.stock.unit": string;
  "rowFilter.stock.quantity": string;
  "rowFilter.stock.sku": string;
  "rowFilter.stock.item_id": string;
  "rowFilter.stock.created_at": string;
}

export interface operations {}

export interface external {}
